### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [z-shell/zsh-diff-so-fancy#5]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) and the [zsh-quickstart-kit](github.com/unixorn/zsh-quickstart-kit), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by ss-o** [comment]
Hey @unixorn,

The license has been added. Thank you for reaching out.

Sincerely,
